version: '3.8'
services:
  eyeblue:
    image: eyeblue/tank:4.0.0
    container_name: eyeblue
    restart: unless-stopped
    networks:
      - tools
    ports:
      - "6010:6010"
    volumes:
      - ./eyeblue/data:/data/build/matter
    environment:
      - PUID= 0
      - PGID= 0
      - UMASK= 022
  enbizcard:
    image: wbsu2003/enbizcard
    restart: unless-stopped
    ports:
      - 22212:80
    networks:
      - tools
  awvs:
    image: secfa/awvs:latest
    ports:
      - "13443:3443"
    cap_add:
      - LINUX_IMMUTABLE
    networks:
      - tools
  gotenberg: #pdf markdown、word、excel转化为pdf
    image: gotenberg/gotenberg:7
    ports:
      - 3100:3000
    networks:
      - tools
  vnstat:
    image: vergoh/vnstat:2.10
    container_name: vnstat
    restart: unless-stopped
    network_mode: host
    environment:  
      - HTTP_PORT=8685
      - TZ=Asia/shanghai
      # - EXCLUDE_PATTERN=^docker
  openblocks:
    image: openblocksdev/openblocks-ce:latest
    container_name: openblocks
    restart: unless-stopped
    ports:
      - 3042:3000
    volumes:
      - ./openblocks:/openblocks-stacks
    networks:
      - tools
  metabase: # BI
    image: metabase/metabase:latest
    ports:
      - 3043:3000
    networks:
      - tools
  memos:
    image: neosmemo/memos:latest
    volumes:
      - ./memos/:/var/opt/memos
    ports:
      - 5230:5230
    networks:
      - tools
  mstream:
    image: linuxserver/mstream:version-v4.7.0
    hostname: MSTREAM
    container_name: mstream
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - USER=admin  
      - PASSWORD=p@ssw0rd
      - USE_JSON=false
      - UMASK_SET=022
    volumes:
      - ./mstream/config/:/config/
      - ./mstream/music/:/music/
    ports:
      - 8230:3000
    networks:
      tools:
        # ipv4_address: 172.168.28.2
    restart: on-failure
  answer:
    image: answerdev/answer
    ports:
      - '9080:80'
    restart: on-failure
    volumes:
      - ./answer:/data
networks:
  tools:
    driver: bridge