services:
  traefik-proxy:
    image: traefik:v2.10
    command: "--api.insecure=true --providers.docker"
    ports:
      - "8081:80"
      - "8082:8080"
    volumes:
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./conf:/etc/traefik/conf
    networks:
      - traefik
    restart: always
networks:
  traefik:
   driver: bridge