x-common: &common
  env_file: ./.env
  restart: always
  networks: 
    - sample
  

version: '3'
services:
  sample.api-dev:
    image: registry.cn-shanghai.aliyuncs.com/galosoft/sample.api:2023.09.09.4
    ports:
      - 7001:80
    environment: &sample-api-env
      - ASPNETCORE_ENVIRONMENT=Production
    deploy:
      replicas: 1
    <<: *common
  sample.api:
    image: registry.cn-shanghai.aliyuncs.com/galosoft/sample.api:2023.09.09.4
    environment: *sample-api-env
    deploy:
      replicas: 3
      update_config:
        order: start-first
    <<: *common
  iaas-admin-ts:
    image: registry.cn-shanghai.aliyuncs.com/galosoft/iaas-admin-ts:2023.09.03.2
    ports:
      - 8080:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
    environment:
      - NODE_ENV=production
    <<: *common
  jaeger:
    image: jaegertracing/all-in-one:1.49
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778 
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      # - 9411:9411
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    networks:
      - sample
  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - 9411:9411
    networks:
      - sample  
networks:
  sample:
   driver: bridge