version: '2'
services:
  jimureport-mysql:
    image: registry.cn-shanghai.aliyuncs.com/galosoft/jimureport-mysql:1.5.4
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
    ports:
      - 3307:3306
    networks:
      - jimureport

  jimureport:
    image: registry.cn-shanghai.aliyuncs.com/galosoft/jimureport:1.5.4
    restart: always
    container_name: jimureport
    ports:
      - 8085:8085
    networks:
      - jimureport
networks:
  jimureport:
    driver: bridge